name: Update Waka stats

on:
  workflow_dispatch:
  schedule:
    # Runs every 24 hours
    # - cron: "0 */24 * * *"

jobs:
  update-readme:
    name: Update my Waka stats
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}